apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: gcr.io/push-notification-api-413106/django-app:v1
        ports:
        - containerPort: 8000
        command: ["gunicorn", "push_notification_api.wsgi:application", "--bind", "0.0.0.0:8000"]
