# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Define environment variable
ENV DJANGO_SETTINGS_MODULE push_notification_api.settings

# Run the Kafka script when the container launches
CMD ["python", "kafka_consumer_script.py"]
